### ISSUE TITLE
Not showing status on status page

### ISSUE THREAD

**Issue by Ryanhindman6654** [statsig-io/statuspage#11]
Hello,

  I followed all the directions but my status page show no data collected. Is there a way to fix this and if so how do I go about doing that?

 Thank you

**Comment by roim** [comment]
Hi Ryan,

Is the GitHub action to update status running? If it fails, what error do you see?

My hunch is that you created a private repository (since I can't see your fork) but don't have actions setup to run on those.

**Comment by Ryanhindman6654** [comment]
Where do I check the GitHub Action? The Repository is public according to my account.

**Comment by vijaye-statsig** [comment]
@Ryanhindman6654 if you got it working, could you post the solution for others in the same situation?

**Comment by Ryanhindman6654** [comment]
I just set the health-check.yml in .github/workflows to run every 5 minute then it started working.
