### ISSUE TITLE
Health check isn't updating

### ISSUE THREAD

**Issue by PadowYT2** [statsig-io/statuspage#12]
The health check file worked, but it didnt update it on the website for some reason
![image](https://user-images.githubusercontent.com/71085027/136343478-9807e2b4-20e8-4fc4-8f9c-b32d3b4805b2.png)
![image](https://user-images.githubusercontent.com/71085027/136343505-7381a4fe-9e64-42f2-9d67-f468fe081a8d.png)

**Comment by roim** [comment]
Hey, I’ll take a look this week. Sorry—missed the first update here.

**Comment by roim** [comment]
Is the repo of either of you public? Would love to take a look directly.

If it’s private, we might be missing some configuration to commit to the repo, but I could add a token param to the GitHub workflow we use.

**Comment by roim** [comment]
I can't repro this and the public repos I looked at all work fine.

1/ Do you have more info I could use to debug/repro?
2/ Are files in `logs/` being written to when the health check runs?
3/ Any output from the GitHub Action that you could paste here?

**Comment by elightcap** [comment]
I feel like this is an issue with github actions.  In my instance, the workflow does not run at all. Checking the actions tab shows the workflow has never run, and the logs dir has never been updated.

I did find this support case which could explain things.  https://github.community/t/no-assurance-on-scheduled-jobs/133753

**Comment by PadowYT2** [comment]
I'm so sorry for not responding, now I don't use status pages anymore, so not sure what happend/how to fix

If this can be closed, I'll close

**Comment by vijaye-statsig** [comment]
CLosing -- no repro
