### ISSUE TITLE
It freezes

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [statsig-io/statuspage#17]
in github actions it keep saying in progress and that's it really

you can check it out: https://github.com/EsmailELBoBDev2/statuspage/actions/workflows/health-check.yml

**Comment by tore-statsig** [comment]
I get "page not found" from the link you provided.  Looking at the repo, you appear to have removed the github actions.

Was that intentional?  Is this still an issue?

**Comment by EsmailELBoBDev2** [comment]
Yes, i removed it becuase i started to use `cstate` instead but it's still an issue yes and i was getting sometimes build error and literally all of my links were refusing to connect (shows my website is down but it's not) if you want i can setup it again for you

**Comment by vijaye-statsig** [comment]
Please reopen this if you can repro the issue on a clean fork.

**Comment by EsmailELBoBDev2** [comment]
Alright, opened again: https://github.com/EsmailELBoBDev2/statuspage

**Comment by EsmailELBoBDev2** [comment]
hmm, i'm not sure if github would notify or not on closed issues so here we go @vijaye-statsig

**Comment by vijaye-statsig** [comment]
If you look at the raw logs of the action, GitHub is waiting to pick a runner, and you might have run out of free runner capacity.

I noticed you have rescheduled these checks to run every 5mins, which would cause this.  I would recommend going back to once every 30 mins and see if it resolves your issue.

**Comment by EsmailELBoBDev2** [comment]
Okay, i did that and still no luck still freezing
