### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by dorianim** [statsig-io/statuspage#18]
Hi,

I love this idea, and I will migrate to it from uptimerobot.
One thing that I miss, though, is notifications.
How about using something like [shoutrrr](https://github.com/containrrr/shoutrrr) to send out notifications when a service goes down?

Regards,
Dorian

**Comment by vijaye-statsig** [comment]
Sounds like a good idea - could you send a PR please?

**Comment by dorianim** [comment]
I'm currently working on my own solution for this, which is completely based on glolang. 
But I don't know, when I will have time to finish it.

**Comment by IzumiSenaSora** [comment]
@vijaye-statsig bro i added pull request which add support for SMTP Mail Notification support + incident report support! https://github.com/statsig-io/statuspage/pull/24

**Comment by Zaid-maker** [comment]
> I'm currently working on my own solution for this, which is completely based on golang. 
> But I don't know, when I will have time to finish it.

Been 2 years Lmao!

**Comment by IzumiSenaSora** [comment]
> > I'm currently working on my own solution for this, which is completely based on golang.
> > But I don't know, when I will have time to finish it.
> 
> Been 2 years Lmao!

I made mine based on bash already and replaced all from this to mine! And it's working flawlessly!
