### ISSUE TITLE
Incident Report in (Demo)

### ISSUE THREAD

**Issue by IzumiSenaSora** [statsig-io/statuspage#22]
Hello!... i just checked demo of statsig.io
It seems like there is a incident management system you guys added there!... but not here.... can i know the reason why?....
Just Curious!

**Comment by tore-statsig** [comment]
Hello!

Thanks for the feedback.  We can definitely add that to the open source statsuspage.  Or, if you want to take a stab, we welcome PRs here

**Comment by IzumiSenaSora** [comment]
Its seems you guys switch from markdown to json in demo statsig.io ...
May i know the reason?

**Comment by IzumiSenaSora** [comment]
@tore-statsig i just added pull request https://github.com/statsig-io/statuspage/pull/24 which add support for incident report can you can check it out?
